# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ kernel ]
  pull_request:
    branches: [ kernel ]

jobs:
  build:

    runs-on: [self-hosted]

    steps:

    - name: Install dependencies
      run: |
        git init
        sudo apt-get update
        sudo apt-get install ccache gcc wget libopenmpi-dev openmpi-bin liblapack-dev 
        python -m pip install --upgrade pip 
        pip install numpy scipy mpi4py cython
        git submodule update --init --recursive
        cd adpy && pip install . && cd ..
        make
        pip install .
        ./install_deps.sh
        tests/setup_tests.sh

    - name: test
      run: |
        ./tests/run_tests.sh
